weatherapp:
  name: weatherapp
  config:
    global: global-cm
    bg: green-configmap
    api: weatherapikey-cm
    flags: flags-cm
  image:
    name: gingerous/weatherapp_k8s
    tag: 1.1.3
  service:
    canary:
      name: weatherapp-canary
      type: ClusterIP
      protocol: TCP
      port: 80
      targetPort: 8000
    stable:
      name: weatherapp-service
      type: ClusterIP
      protocol: TCP
      port: 80
      targetPort: 8000


secrets:
  weatherapp:
    name: weatherapp-secret
    refresh: 30s
    target:
      name: weatherapp-secret-env
    key:
      name: API_KEY

  vault:
    name: vault-backend
    server: "http://vault.default.svc.cluster.local:8200"
    key:
      path: weatherapp
      property: WEATHER_API_KEY
    auth:
      name: vault-token
      key: token

ingress:
  name: applications-ingress
  classname: nginx
  weatherapp:
    host: weather.ginger-ous.click
replicaCount: 2
