weatherapp:
  name: weatherapp
  config:
    global: global-cm
    bg: blue-configmap
    api: weatherapikey-cm
    flags: flags-cm
  image:
    name: gingerous/weatherapp_k8s
    tag: 1.1.3
  service:
    name: weatherapp-service
    type: ClusterIP
    protocol: TCP
    port: 80
    targetPort: 8000
ingress:
  name: applications-ingress
  classname: nginx
  weatherapp:
    host: weather.ginger-ous.click
replicaCount: 4
APP_VERSION: 1.1.0
