weatherapp:
  name: weatherapp
  config:
    name: green-configmap
  image:
    name: gingerous/weatherapp_k8s
    tag: 1.0.2
  service:
    name: weatherapp-service
    type: ClusterIP
    protocol: TCP
    port: 80
    targetPort: 8000
ingress:
  name: applications-ingress
  classname: nginx
  weatherapp:
    host: weather.ginger-ous.click
replicaCount: 2
