apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secrets.vault.name }}
  namespace: default
spec:
  provider:
    vault:
      server: {{ .Values.secrets.vault.server }}
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: {{ .Values.secrets.vault.auth.name }}
          key: {{ .Values.secrets.vault.auth.key }}
