apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secrets.vault.name }}
spec:
  provider:
    vault:
      server: {{ .Values.secrets.vault.server }}
      path: {{ .Values.secrets.vault.path }}
      version: {{ .Values.secrets.vault.version }}
      auth:
        tokenSecretRef:
          name: {{ .Values.secrets.vault.auth.name }}
          key: {{ .Values.secrets.vault.auth.key }}
