apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.weatherapp.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    canary:
      canaryService: {{ .Values.weatherapp.service.canary.name }}
      stableService: {{ .Values.weatherapp.service.stable.name }}
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
      - setWeight: 100
  selector:
    matchLabels:
      app: {{ .Values.weatherapp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.weatherapp.name }}
    spec:
      containers:
      - name: {{ .Values.weatherapp.name }}
        image: "{{ .Values.weatherapp.image.name }}:{{ .Values.weatherapp.image.tag }}"
        envFrom:
        - configMapRef:
            name: {{ .Values.weatherapp.config.global }}
        - configMapRef:
            name: {{ .Values.weatherapp.config.bg }}
        - configMapRef:
            name: {{ .Values.weatherapp.config.api }}
        - configMapRef:
            name: {{ .Values.weatherapp.config.flags }}
      imagePullSecrets:
      - name: docker-cred
